token:
    expiration_time: 864000000
    secret : '{cipher}AYBXp/x0ErWy/SD+jxVihI4UFLaFdn8yB5oEB7p4z+iexGB8++esLvfL6XoHjs2fo/NHE6EwRtmIWNrMml2349vrZ8eDQk0tnku8Ss5NwXSWy3+daSnY8tCFuEHM1SGHuphS/SdjkLMoMAPN5g9ccAYyTmDz9CA8A0gdT9w3JMVVQEGkmG5LKBDv/3QvbpDOE99q53O+CXOgouEt6E+YDzSswTl6qaNYBaskZNszF0q+3P8z2dwbdx5YIbaDlI3zTlIu1x9QBC8uuhtJ5Y/F1GBGkpmzy/PWBJ7EwGk+SE8RKxNvbrPprWzBj/lLq4iTyMb8DK3uENi6GREif8WWuE1K998TIqa66VYF5nRXCB9ql4Gp4Ip2KwbU4O7LWZFz54Z1SAKFQdBm0Fqxgg7nu4NEbSMwyIrSjoz6WV+E+XCteUd4NEMMhLsb+mjJJM0pHEzis6fs9jenNosirr2eSrCoxRgg0fdwm2CSzts42+kIxto0xgLfezGk0F05MTZJbR/ckQjWGXOHZh4vof5Pi9IHi4szfoTm+k1cMs0qOKOIbxN/AcplVhybMSPbP5qoYMQ='

gateway:
    ip: 203.249.126.181

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'
    username: sa
    password: '{cipher}AYCc+j79XMm8iOqhAq1H7joyV+NmbRYbVo5uoK2fF49i/XlIYJ5la2yKDOhazNCunepbA60JagLUm+04BlwsPii1kcQ8oFuAkN/zphcVNpfy5vlRflrtjFqU4JonSaDVzDWMCwW7Y0C4xU/lPT48c3g+XSEvbtcnN7HwO3NXDbZTlwKFxPfaDDF8KQSFqlNW9X2xuouJ2p5GKI5Ef6LiaF20V/5H/cgcgfYm//YaDN3nO4pGeMaYOYNKVNz+/VPgYk/+Z/+jY7Wlfq2+KoDxQapXtJ2hygnVPh1vTYMLtSVyWjSlkA1BXoFIrD7tMkvfvVHlcE0MgPmSGP6fkMVE64GGwONnZFFgRVIGMeUXLcXOJlE1AD/RrPThkoHV7zEy+Aq+yoTyBffZnWXPMZSMe2shwINv7H9JSJ4KDaekpGLHmyIYtW9js9nbk/igVXElI/s977bwpvw3hPmKN7mdBpjErre0dbpI7kli9LT6nHu5r47FcRUYwBKOzxuejoAvqGbmdv7HnHOLf7spAFcCzLc772XcVDa9eISnJ0gqS7cVgg=='

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty : There is no Item.